# Generated by Django 3.1.4 on 2020-12-15 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201215_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date',
            new_name='article_date',
        ),
    ]
