# Generated by Django 3.1.4 on 2020-12-18 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_article_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='audio_file',
        ),
    ]
