# Generated by Django 3.1.4 on 2020-12-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_article_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='audio',
            field=models.FileField(blank=True, default='none', null=True, upload_to='audio/'),
        ),
    ]
