# Generated by Django 3.1.4 on 2020-12-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='category',
            field=models.CharField(default='music', max_length=150),
        ),
    ]
