# Generated by Django 3.1.4 on 2020-12-24 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201222_0529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
